{% set name = "css_inline" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/css_inline-{{ version }}.tar.gz
  sha256: 6cc37e956d6c44ad2e0c230d0d111c7f61a47117bab179f6ab59f23bf33b1caa

build:
  number: 0
  skip: true  # [py<37]
  script:
    - pushd css-inline && cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml && popd
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.1                       # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.1
    - pip
  run:
    - python

test:
  imports:
    - css_inline
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Stranger6667/css-inline
  summary: High-performance library for inlining CSS into HTML 'style' attributes
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  dev_url: https://github.com/Stranger6667/css-inline/tree/master/bindings/python

extra:
  recipe-maintainers:
    - synapticarbors
