context:
  version: "0.14.6"

package:
  name: css_inline
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/css_inline/css_inline-${{ version }}.tar.gz
  sha256: a6ac1411bc9524cab0de59fe87bf1779c822fd6f38d789a037879ebcbcc3e14b

build:
  number: 0
  skip: match(python, "<3.7")
  script:
    - pushd css-inline && cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml && popd
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python - python - cross-python_${{ target_platform }} - crossenv - maturin >=1.1
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.1
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - css_inline
      pip_check: true

about:
  summary: "High-performance library for inlining CSS into HTML 'style' attributes"
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  homepage: https://github.com/Stranger6667/css-inline
  repository: https://github.com/Stranger6667/css-inline/tree/master/bindings/python

extra:
  recipe-maintainers:
    - synapticarbors
