context:
  version: "0.17.0"

package:
  name: css_inline
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/css_inline/css_inline-${{ version }}.tar.gz
  sha256: f0f3c59fd793d53595910faca14b5bf5b86ff692c1d7f664f86028ee24d8eb2f

build:
  number: 1
  skip: match(python, "<3.9")
  script:
    - pushd css-inline && cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml && popd
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1.1
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.1
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - css_inline
      pip_check: true

about:
  summary: "High-performance library for inlining CSS into HTML 'style' attributes"
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  homepage: https://github.com/Stranger6667/css-inline
  repository: https://github.com/Stranger6667/css-inline/tree/master/bindings/python

extra:
  recipe-maintainers:
    - synapticarbors
